name: '${name}'
version: '${version}'
main: '${main}'
folia-supported: true
depend:
  - BukkitOfUtils
softdepend:
  - PlaceholderAPI

commands:
  rules:
    description: "Open the server rules menu."
    permission: "justrules.commands.rules"
    aliases:
      - rule